# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hacking on things...
#email: aaron.ott@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Always be learning. Push push push...
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://ado.im" # the base hostname & protocol for your site
#twitter_username: aaronott
#github_username:  aaronott

permalink: /:categories/:title.html

# Build settings
markdown: kramdown

# Handling Reading
exclude:  ["publish.sh"]

include:  ['.htaccess']

# Load these plugins
plugins: ["jekyll-email-protect", "uglifier", "jekyll-deploy"]
